# Site configuration for SUS-Risk GitHub Pages
title: "PRIN 2020 - 20205L79R8 - SUS-RISK"
description: "Towards a holistic approach to sustainable risk management in agriculture"

# GitHub Pages settings
url: "https://prinsus-risk.github.io"
baseurl: "/SUS-Risk"

# Theme and plugins
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-readme-index

# Navigation (using header_pages for minima theme)
header_pages:
  - about/Project_Overview.md
  - about/team.md
  - research/publications.md
  - research/work-packages.md
  - research/Deliverables_Reports_PB.md
  - research/Projec_Impact.md
  - about/contact.md

# Minima theme settings
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/PRINSUS-RIsk/SUS-Risk" }

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - LICENSE
