title: "PRIN 2020 Agricultural Risk Management"
description: "Towards a holistic approach to sustainable risk management in agriculture"
url: "https://prinsus-risk.github.io/SUS-Risk/"
baseurl: ""

theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-feed

navigation:
  - title: Home
    url: /
   - title: team
    url: /about/team.md
  - title: About
    url: /about/
  - title: Research
    url: /research/
  - title: Pubblications
     url: /research/pubblications.md
   - title: work-packages
     url: /research/work-packages.md  
  - title: Resources
    url: /resources/
  - title: News
    url: /news/
  - title: Contact
    url: /contact/
